### ISSUE TITLE
installing  steppyngstounes

### ISSUE THREAD

**Issue by alsmairat** [usnistgov/steppyngstounes#4]
Dear all
I have been trying to install steppyngstounes on Intellij using add package but unfortunately I get the following error:

```
Looking in indexes: https://github.com/usnistgov/steppyngstounes/

ERROR: Could not find a version that satisfies the requirement steppyngstounes (from versions: none)
ERROR: No matching distribution found for steppyngstounes.
```

I tried to use pip install git+  command on command prompt

```
  ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Salah.SALAH\\AppData\\Local\\Temp\\pip-req-build-yhs67s88\\setup.py'"'"'; __file__='"'"'C:\\Users\\Salah.SALAH\\AppData\\Local\\Temp\\pip-req-build-yhs67s88\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Salah.SALAH\AppData\Local\Temp\pip-pip-egg-info-xhpg6ahq'
         cwd: C:\Users\Salah.SALAH\AppData\Local\Temp\pip-req-build-yhs67s88\
    Complete output (28 lines):
    Traceback (most recent call last):
      File "c:\program files\python39\lib\site-packages\pkg_resources\__init__.py", line 2851, in get_entry_map
        ep_map = self._ep_map
      File "c:\program files\python39\lib\site-packages\pkg_resources\__init__.py", line 2813, in __getattr__
        raise AttributeError(attr)
    AttributeError: _ep_map

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Salah.SALAH\AppData\Local\Temp\pip-req-build-yhs67s88\setup.py", line 6, in <module>
        setuptools.setup(
      File "c:\program files\python39\lib\site-packages\setuptools\__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "c:\program files\python39\lib\site-packages\setuptools\__init__.py", line 142, in _install_setup_requires
        dist = MinimalDistribution(attrs)
      File "c:\program files\python39\lib\site-packages\setuptools\__init__.py", line 134, in __init__
        distutils.core.Distribution.__init__(self, filtered)
      File "c:\program files\python39\lib\site-packages\setuptools\dist.py", line 453, in __init__
        for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
      File "c:\program files\python39\lib\site-packages\pkg_resources\__init__.py", line 641, in <genexpr>
        for entry in dist.get_entry_map(group).values()
      File "c:\program files\python39\lib\site-packages\pkg_resources\__init__.py", line 2853, in get_entry_map
        ep_map = self._ep_map = EntryPoint.parse_map(
      File "c:\program files\python39\lib\site-packages\pkg_resources\__init__.py", line 2538, in parse_map
        raise ValueError("Entry points must be listed in groups")
    ValueError: Entry points must be listed in groups
    ----------------------------------------
WARNING: Discarding git+https://github.com/usnistgov/steppyngstounes.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: Ignoring invalid distribution -rotli (c:\users\salah.salah\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -rotli (c:\users\salah.salah\appdata\roaming\python\python39\site-packages)
```

  I am not professional in coding, and very new to programming therefore I copied every thing and pasted it.
I appreciate any help , thanks

**Comment by guyer** [comment]
I'm not sure, but I think the error in Intellij is because it's looking for an index like pypi, rather than a single code repository. I don't know anything about how to configure Intellij.

The second case, `pip install git+https://github.com/usnistgov/steppyngstounes.git` works for me. I don't know what `rotli` is (other than another name for chapati flatbread). The only relevant search item I come up with is https://githubmemory.com/repo/kaiwk/leetcode.el/issues/88, which isn't any help.

Does pip work for you for other things? 
How about with other `git+` repositories?

**Comment by alsmairat** [comment]
pip works with other things

**Comment by alsmairat** [comment]
about git+ did not work with other packages

**Comment by guyer** [comment]
I've installed IntelliJ IDEA 2021.2.1 (Community Edition) for macOS. I have no idea how to even tell it I want to run a Python script, much less how to install packages in its environment. Please either give me explicit steps to match your configuration or I think you will need to approach JetBrains for support.

**Comment by guyer** [comment]
From the comments on https://stackoverflow.com/a/69023337/2019542, it looks like this is resolved?

**Comment by alsmairat** [comment]
It was resolved, and I am very grateful.

Is there an action I need to do after resolving the issue?

**Comment by guyer** [comment]
No action needed. I think you have permission to close the issue, but I will do so.
